# Odoo yaml template for travis-ci
# __version__=0.2.1

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

virtualenv:
  system_site_packages: false

git:
  submodules: false
  depth: false

services:
  - postgresql

addons:
  apt:
    sources:
      # Search your sources alias here:
      # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      # - build-essential                 # Pre-installed
      # - curl                            # Pre-installed
      - expect-dev
      # - less-plugin-clean-css           # Pre-installed
      # - lessc                           # Pre-installed
      - libevent-dev
      - libffi-dev
      - libssl-dev
      # - nodejs                          # Pre-installed
      # - npm                             # Pre-installed
      - python3-dev
      # - python-setuptools               # Pre-installed
      # - wkhtmltopdf                     # Pre-installed
      - zlib1g

before_install:
  # Use Zeroincombenze(R) tools
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --single-branch --depth=1
  - ${HOME}/tools/install_tools.sh -qpt
  - source ${HOME}/devel/activate_tools
  - echo "$PATH"
  - export PYTHONPATH=${HOME}/tools


install:
  - travis_install_env
  # tests of document_ftp and delivery fail. The following two are excluded because they depend on delivery
  # account_invoice_sequential_dates fails with FatturaPA 
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery,account_invoice_sequential_dates,l10n_it_corrispettivi
  # - export INSTALL_OPTIONS="--without-demo=account"
  # - cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .
  # - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/odoo/addons ${HOME}/build/${ODOO_REPO}/addons)

env:
  global:
  - TRAVIS_DEBUG_MODE="2"
  - WKHTMLTOPDF_VERSION="0.12.6"
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" ODOO_TNLBOT="0"


  matrix:
  - LINT_CHECK="1" LINT_CHECK_LEVEL="REDUCED"
  # - TESTS="1" ODOO_TEST_SELECT="NO-CORE" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_TEST_SELECT="NO-CORE" ODOO_REPO="OCA/OCB"
  # - TESTS="1" ODOO_REPO="zeroincombenze/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

