# © 2025 Andrei Levin - Codebeex srl (www.codebeex.com)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
# This code is AI generated by Claude
# noinspection PyStatementEffect
{
    'name': 'Clickable many2many tags',
    'version': '12.0.0.0',
    'category': 'Tools',
    'summary': 'Add widget clickable_many2many_tags',
    'author': 'Codebeex srl',
    'website': 'https://www.codebeex.com',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'web'
    ],
    'data': [
        'views/assets.xml'
    ],
}
