# Module is generated by Clude.ai
# © 2025 Andrei Levin - Codebeex srl (www.codebeex.com)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
# noinspection PyStatementEffect
{
    'name': 'MuK Theme Sum Fix',
    'version': '12.0.1.0.0',
    'category': 'Theme/Backend',
    'summary': 'Fix sum visibility in MuK Backend Theme',
    'description': """
        Improves visibility of sum totals in list views when using MuK Backend Theme.
    """,
    'depends': [
        'web',
        'muk_web_theme',
    ],
    'data': [
        'views/assets.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
